### ISSUE TITLE
Feedback from Eurofins

### ISSUE THREAD

**Issue by johnluther** [cta-wave/mezzanine#1]
Comments relating to sections of the document “wave-device-playback-stream-production-annotation-2020-04-23”:

- S3.1: The video does not contain an identifier for the stream (e.g. the letter “A”, “B”)
- S3.1: The QR codes are transparent and will be difficult to read against the video background, we suggest mounting them on a fully opaque white square
- S3.1: There are no flashes included in the video for AV sync (or at least no reserved area from a screen real estate perspective)
- S3.1: For automated AV sync testing a sequence of beeps should be used which must be synchronised with the flashes in the video. We would recommend a repeating pattern e.g. 120ms beeps such as '1s, 1s, 2s, 1s, 2s, 3s' to ensure any misalignment is captured. To make automated capture easy it may be necessary to silence spoken audio either side of the beeps.
- 3.3.5: Could you/someone please clarify the distinction being made between media time and timecode? We are keen to not confuse anyone (or in fact ourselves) if/when commenting on this point and would like to be clear.

Comments relating to the stream sample which have no current document reference:

- No document reference / should be S3.1: Human readable information: there is no visual text representation of the frame count, which would help manual testing / deferred analysis.
- No document reference / should be S3.1:  For manual AV sync testing we would recommend using the original audio track
- No document reference / should be S3.1: a constant tone in the background in addition to spoken audio and beeps may make automated testing difficult and provide inconsistent results. We would suggest having an audio tone at the start (for audio start up delay) and end, and at a consistent jump to point (e.g. 20s) to enable automated checking. Additionally, could testing for all segments being presented in the correct order be inferred by passing the AV sync criteria for both manual and automated testing?

**Comment by haudiobe** [comment]
Call on May 28, 2020:
_S3.1: The video does not contain an identifier for the stream (e.g. the letter “A”, “B”)_
*Agreed*

_S3.1: The QR codes are transparent and will be difficult to read against the video background, we suggest mounting them on a fully opaque white square_
*Agreed*

_S3.1: There are no flashes included in the video for AV sync (or at least no reserved area from a screen real estate perspective)_
Some clarification: flashes white a random prescribed intervals (kind of every 1-2 seconds) seconds to check synchronization of audio video - comes aligned with the audio beep. There is a separate dedicated area that flashes white for a duration of 120ms (can attach a light sensor).
*Agreed*

_S3.1: For automated AV sync testing a sequence of beeps should be used which must be synchronised with the flashes in the video. We would recommend a repeating pattern e.g. 120ms beeps such as '1s, 1s, 2s, 1s, 2s, 3s' to ensure any misalignment is captured. To make automated capture easy it may be necessary to silence spoken audio either side of the beeps._
*Agreed*

_3.3.5: Could you/someone please clarify the distinction being made between media time and timecode? We are keen to not confuse anyone (or in fact ourselves) if/when commenting on this point and would like to be clear._
Media is decimal and fractional seconds. Time Code is counting frames (frame 24 would be 0.96 seconds). PTS timestamps and counter - QR Code are PTS times, and counter is seconds in decimal.
Two features:
- Linear frame number (independent of time, but would be time if multiplied by timescale 1, 2, 3, )
- Actual media time (that expresses the time of the frame in the media in decimal time 10.254 )
@wilaw please check this and get back to @johnluther and @jpiesing 

_Comments relating to the stream sample which have no current document reference:_

_No document reference / should be S3.1: Human readable information: there is no visual text representation of the frame count, which would help manual testing / deferred analysis._
see comment above. seems to be frame count/number from above

_No document reference / should be S3.1: For manual AV sync testing we would recommend using the original audio track_
low-background noise before and after. But we use it for beeps.
*Agreed*

_No document reference / should be S3.1: a constant tone in the background in addition to spoken audio and beeps may make automated testing difficult and provide inconsistent results. We would suggest having an audio tone at the start (for audio start up delay) and end, and at a consistent jump to point (e.g. 20s) to enable automated checking. Additionally, could testing for all segments being presented in the correct order be inferred by passing the AV sync criteria for both manual and automated testing?_
This is about the requirement be able to verify that all samples are played. With the audio need to make sure that every audio sample has a defined start and end tone (apply a different frequency than the beep - could also be a short jingle (identifying) and it is longer - like 1 seconds).
*agreed*

**Comment by nicholas-fr** [comment]
I believe all these points have been addressed except for:

- "To make automated capture easy it may be necessary to silence spoken audio either side of the beeps".
If this is still a concern following #8, the weighting of the original source audio vs the beeps could be adjusted to avoid any detection issues. If that's acceptable, this point can be considered resolved.

- "We would suggest having an audio tone at the start (for audio start up delay) and end, and at a consistent jump to point (e.g. 20s) to enable automated checking."
The irregular AV sync pattern repeats after a configurable duration, which enables checking at known points in the stream. If that is sufficient, then this can be considered resolved once a tone has been added to accompany the start/end frames (work ongoing). 

- "With the audio need to make sure that every audio sample has a defined start and end tone (apply a different frequency than the beep - could also be a short jingle (identifying) and it is longer - like 1 seconds)."
I believe the configurable irregular AV sync pattern addresses this.  If so, this point can be considered resolved.

**Comment by haudiobe** [comment]
Call 2020/07/27: No issues remaining- thanks
