### ISSUE TITLE
Meta-script for creating a full set of annotated mezzanine content

### ISSUE THREAD

**Issue by nicholas-fr** [cta-wave/mezzanine#16]
To avoid manually calling `mezzanine.py` to generate each annotated mezzanine stream, a meta-script should be created to generate a full set of streams.

My understanding is that this currently includes:
 - Generating 1min streams for all the following resolutions:
	320x180
	384x216
	480x270
	512x288
	640x360
	704x396
	720x404
	768x432
	852x480
	960x540
	1024x576
	1280x720
	1600x900
	1920x1080
	2560x1440
	3200x1800
	3840x2160

 - Generating 3min30s streams for 1280x720, 1600x900, 1920x1080

Perform this above using Tears of Steel to create 60fps and 60/1.001fps streams.
Perform this above using the Croatia EBU footage to create 50fps streams.
Each resolution will be labelled starting with 'A' for the lowest resolution, then 'B' and so on.

Such a script has been written and is being tested. 
I'll create a pull request for it once initial testing has been done.

**Comment by haudiobe** [comment]
Call 2020/07/27: @nicholas-fr will take care, but only a matter of execution

**Comment by nicholas-fr** [comment]
This issue was resolved by the creation of `metamezz.py` in pull request #17
