### ISSUE TITLE
Generate a BBB Content for Ad Insertion

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/mezzanine#18]
It proposed to generate another set of mezzanine content for BBB, that can be used for ad insertion. This part should be including some of the trailer in order to have some transition. The duration of the content should be 30 seconds.

**Comment by nicholas-fr** [comment]
Initial test content for this was uploaded in this folder:
https://dash.akamaized.net/WAVE/Mezzanine/new/?cache=clear
- ad_bbb_AD-A1_1280x720@30_30.mp4
- ad_bbb_AD-B1_1920x1080@30_30.mp4

Generated using the Big Buck Bunny Trailer as the source (33 seconds long), truncated to 30 seconds, converted from 25fps to 30fps.

**Comment by jpiesing** [comment]
I think 25Hz versions of this may also be useful.

**Comment by nicholas-fr** [comment]
25Hz versions now uploaded:
- ad_bbb_AD-A1_1280x720@25_30.mp4
- ad_bbb_AD-B1_1920x1080@25_30.mp4

**Comment by nicholas-fr** [comment]
This mezzanine content was moved here:
https://dash.akamaized.net/WAVE/Mezzanine/new/2021-03-31/
Feedback on the labels to use, duration and other aspects are welcome.

**Comment by nicholas-fr** [comment]
The latest versions are here:
https://dash.akamaized.net/WAVE/Mezzanine/under_review/2021-06-30/
The start/end frames now have annotations & QR codes, in line with the latest mezzanine changes.

**Comment by nicholas-fr** [comment]
The latest versions of both "ad" mezzanine and new shorter mezzanine content can be found here:
https://dash-large-files.akamaized.net/WAVE/Mezzanine/under_review/2021-07-29/
To differentiate this mezzanine content from the rest:
- Main mezzanine content is prefixed with `splice_main_`, followed by the content-related prefix (i.e. "croatia" or "tos").
- "Ad" mezzanine content  is prefixed with `splice_ad_`, followed by the content-related prefix (i.e. "bbb").

The rest of the mezzanine file naming convention remains the same.

**Comment by jpiesing** [comment]
@rbouqueau Please could you check that these files are what you expect based on our discussions. If they are, please go ahead and encode them.

**Comment by rbouqueau** [comment]
I've generated a first set of streams:
- http://reference.dashif.org/dash.js/latest/samples/dash-if-reference-player/index.html?mpd=https://dash.akamaized.net/WAVE/vectors/2021-07-29/splice/25/stream.mpd
- http://reference.dashif.org/dash.js/latest/samples/dash-if-reference-player/index.html?mpd=https://dash.akamaized.net/WAVE/vectors/2021-07-29/splice/30/stream.mpd

**Comment by nicholas-fr** [comment]
The latest versions of both "ad" mezzanine and new shorter mezzanine content can be found here:
https://dash-large-files.akamaized.net/WAVE/Mezzanine/under_review/2021-07-30/

The only change is that the splice_main_tos_* streams now have 48kHz audio (instead of 44.1kHz).

**Comment by rbouqueau** [comment]
Ok thanks. I had put a resampler. Doing the resampling before or after should not affect the result. So I won't re-generate unless asked otherwise.

**Comment by nicholas-fr** [comment]
Thanks, makes sense. Just wanted to make sure the correct content was there for future stream generation.

**Comment by nicholas-fr** [comment]
Content for splicing/ad insertion can now be created and is part of mezzanine release v2.
