### ISSUE TITLE
Generate Slate content

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/mezzanine#19]
Content that can be easily filled if an ad slot and the duration are not matching.

**Comment by haudiobe** [comment]
Proposal: Add a CTA WAVE logo on a black screen and movement will be determined by the overlay

**Comment by jpiesing** [comment]
I'm still not completely sure what is meant by slate content.

Do you mean 15s with (for example) WAVE logo on an otherwise black screen?

Would slate content benefit from burnt-in timecode (etc)?

**Comment by nicholas-fr** [comment]
I believe we concluded this was not needed and the mezzanine created for splicing was sufficient (to address #18), which is now part of approved mezzanine release v2.

As such I propose to close this issue or clarify what additional content is still needed.

**Comment by nicholas-fr** [comment]
2021-09-14 DPCTF test runner telco: 
Agreed to create 5 second video mezzanine with a CTA logo and overlays, for 720p and 1080p for 25fps, 30fps and 29.97fps.

**Comment by gitwjr** [comment]
Close. Can reopen if needed.
