### ISSUE TITLE
QR code capture on smaller devices with GoPro camera

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/mezzanine#24]
In lieu of a observation framework GitHub repositry we are raising this issue here as this may have impact on the mezzanine content.

While testing QR code capture across a range of devices, frame rates and resolutions using the mezzanine content we have found issues when capturing with a GoPro from small screen such as a mobile phone, an iPad and a laptop. Would it be possible to re-run the previously shown demo against a mobile phone rather than a TV to help quickly confirm if changing to a better camera will overcome this issue? If it will we can quickly move onto a better camera.

The table below shows a subset of tests that we have run and indicates that the percentage of QR codes that we were able to decode. 
  | tos_A1_480x270@30_60.mp4 | tos_A1_480x270@59.94_60.mp4 | tos_A1_480x270@60_60.mp4 | tos_L2_1920x1080@30_60.mp4 | tos_L2_1920x1080@59.94_60.mp4 | tos_L2_1920x1080@60_60.mp4
-- | -- | -- | -- | -- | -- | --
TV | 100% | 100% | 100% |   | 100% | 100%
Laptop (dark room  with careful light adjustment and settings) | 59.00% | 51.10% | 54.94% | 100.00% | 99.80% | 99.60%
iPad(dark room with careful light adjustment and settings) |   |   |   | 0% |   |  
Phone(dark room with careful light adjustment and settings) |   |   |   | 0% | 0% |

**Comment by jpiesing** [comment]
Here are the results from playing 30Hz mezzanine streams on an Android tablet with VLC with the camera being a Sony RX100M2 recording at 50Hz. Streams 00000 to 00012 correspond to mezzannine streams A1 to L1 respectively.

- 00000.MTS – 100% detected/played
- 00001.MTS – 3 frames not captured well by the camera + 1 dropped by the player
- 00002.MTS – 100% detected/played
- 00003.MTS – 100% detected/played
- 00004.MTS – 3 frames not captured well by the camera + 1 dropped by the player
- 00005.MTS – 3 frames not captured well by the camera + 1 dropped by the player + 2 first frames not played
- 00006.MTS – 1 frame not captured well by the camera
- 00007.MTS – 1 frame not captured well by the camera
- 00008.MTS – 2 frames not captured well by the camera + 4 first frames not played
- 00009.MTS – no content recorded
- 00010.MTS – 1 frame not captured well by the camera + 3 first frames not played
- 00011.MTS – 1 frame not detected by the script
- 00012.MTS –  1 frame not played

(from @nicholas-fr )
Overall, only 1 detection issue with the script.
And a few detection issues as the frames were not quite captured clearly enough by the camera, possibly as it was recorded in 50fps.

Here’s an example. Other instances were generally slightly worse than this (more faded).

![image](https://user-images.githubusercontent.com/8490792/107563084-f14af580-6be0-11eb-8630-63fb5b164d61.png)

**Comment by yanj-github** [comment]
Closing because alternative camera we have doesnt seems to have same problem. Is is due to limmitation to the specific camera.
