### ISSUE TITLE
Bit pattern for additional testing automation

### ISSUE THREAD

**Issue by nicholas-fr** [cta-wave/mezzanine#28]
Current WAVE testing is designed for black-box testing of devices, using a camera, without requiring manufacturer involvement.

However, there are also cases where a manufacturer may want to do more in-depth white-box testing. Having this pattern would make the WAVE test material more useful for such testing.

As such, this is not in any way intended as a replacement of any of the work ongoing on the test harness.
Processing of a bit pattern such as this is easier to automate than a QR code which changes position in each successive frame.

Composition of the pattern in order from top to bottom:
- 2 black lines,
- 1 calibration line of bits with a value alternating between 0b1 and 0b0, starting with 0b1,
- 2 lines of data, each starting with 2 calibration bits (each the inverse of the bit directly above),
- 1 black line.

There is a margin of 5 black "bits" to the left and of 3 black "bits" to the right of the pattern.

Each "bit" in the pattern is a 2x2 pixel square, for a video resolution of 480x270.
The _relative_ position and size of the bits remains the same for higher video resolutions.

Data lines contain in order (left to right, top to bottom), starting with the LSB ending with MSB:
- current frame number (24 bit), 
- total number of frames in stream (24 bit), 
- frame rate * 1000 (17 bit), 
- horizontal resolution (13 bit), 
- vertical resolution (13 bit)

![image](https://user-images.githubusercontent.com/9865551/113004882-3c5e9f00-9174-11eb-8a64-0ebb876ca1b9.png)

Please share any comments or questions you may have.

**Comment by andyburras** [comment]
The bit pattern doesn't look to be robust as there is no error correction/validation component? So there is no way to detect if it has been misread.

Because the bit pattern is at a fixed postion then if captured by a camera, the patterns on subsequent frames may intermingle and corrupt the pattern. As an illustration here is a camera frame showing 2 mezzanine QR codes. "Cycling" the position of the codes prevents them interfering.

![GH010112_1749](https://user-images.githubusercontent.com/28623246/113696207-9a860780-96c9-11eb-9025-2e7f94265e8d.png)


I don’t really understand what problem the bit pattern is supposed to solve?

**Comment by nicholas-fr** [comment]
The goal of this is to make it easier for TV manufacturers to use the WAVE test material for white-box testing without needing to use a camera.

**Comment by cta-source** [comment]
We have a v0.1 specification for the Mezzanine format specification, which includes this information.  Leaving this issue open due to the question posed by @andyburras;

> The bit pattern doesn't look to be robust as there is no error correction/validation component? So 
> there is no way to detect if it has been misread.

**Comment by nicholas-fr** [comment]
To further elaborate on the answer to this question, the low density bit pattern (LDBP) supplements, but does not replace, the QR codes. The QR codes are designed for black-box testing of devices, using a camera to capture device video output, without requiring manufacturer involvement. However, there are also cases where a manufacturer may want to do more in-depth white-box testing, and the LDBP makes the test content more useful for such testing. Processing of the LDBP image is easier to automate for white-box testing than a QR code which changes position in each successive frame. With white-box testing, error correction is not necessary, as video data is processed directly within a device. 

As there has been no further comments on this, and the LDBP is part of the approved mezzanine release v2, I believe this issue can be closed. New issues can be raised if there are any remaining questions or concerns.
