### ISSUE TITLE
Mezzanine approval process

### ISSUE THREAD

**Issue by nicholas-fr** [cta-wave/mezzanine#30]
Here is a proposed mezzanine stream approval process:

1. Enter issues in GitHub for bugs, feature requests or stream requests (e.g. new resolutions, variants)
2. Review and agree on GitHub issue resolution in DPCTF call
3. Implement DPCTF decision: update scripts and/or encode new mezzanine content 
4. Upload new mezzanine content to https://dash.akamaized.net/WAVE/Mezzanine/new/
5. Announce new content availability via email to DPCTF reflector and open 2 week review period
6. Resolve issues in DPCTF calls
7. Once approved move new content to https://dash.akamaized.net/WAVE/Mezzanine/
8. If older versions of the mezzanine streams exist, delete them (or archive them - to be determined)
9. Update CHANGELOG.md with reference to issues describing changes implemented and the files updated

See below for an example CHANGELOG.md:

# CTA WAVE Mezzanine Changelog
**Version 1 (2021-XX-XX)**
- Mezzanine for 15/30/60 fps and corresponding fractional rates 14.985/29.97/59.94 fps
- Resolutions from 480x270 (label A) to 3160x2160 (label O), as required for the [WAVE test content](https://docs.google.com/spreadsheets/d/1hxbqBdJEEdVIDEkpjZ8f5kvbat_9VGxwFP77AXA_0Ao/)
- 1080p29.97/30/59.94/60 streams with second audio track
- New files:

	- tos_A1_480x270@14.985_60.mp4
	- tos_A1_480x270@15_60.mp4
	- tos_A1_480x270@29.97_60.mp4
	- tos_A1_480x270@30_60.mp4
	- tos_A1_480x270@59.94_60.mp4
	- tos_A1_480x270@60_60.mp4
	- tos_B1_512x288@29.97_60.mp4
	- tos_B1_512x288@30_60.mp4
	- tos_B1_512x288@59.94_60.mp4
	- tos_B1_512x288@60_60.mp4
	- tos_C1_640x360@29.97_60.mp4
	- tos_C1_640x360@30_60.mp4
	- tos_C1_640x360@59.94_60.mp4
	- tos_C1_640x360@60_60.mp4
	- tos_D1_704x396@29.97_60.mp4
	- tos_D1_704x396@30_60.mp4
	- tos_D1_704x396@59.94_60.mp4
	- tos_D1_704x396@60_60.mp4
	- tos_E1_720x404@29.97_60.mp4
	- tos_E1_720x404@30_60.mp4
	- tos_E1_720x404@59.94_60.mp4
	- tos_E1_720x404@60_60.mp4
	- tos_F1_768x432@29.97_60.mp4
	- tos_F1_768x432@30_60.mp4
	- tos_F1_768x432@59.94_60.mp4
	- tos_F1_768x432@60_60.mp4
	- tos_G1_852x480@29.97_60.mp4
	- tos_G1_852x480@30_60.mp4
	- tos_G1_852x480@59.94_60.mp4
	- tos_G1_852x480@60_60.mp4
	- tos_H1_960x540@29.97_60.mp4
	- tos_H1_960x540@30_60.mp4
	- tos_H1_960x540@59.94_60.mp4
	- tos_H1_960x540@60_60.mp4
	- tos_I1_1024x576@29.97_60.mp4
	- tos_I1_1024x576@30_60.mp4
	- tos_I1_1024x576@59.94_60.mp4
	- tos_I1_1024x576@60_60.mp4
	- tos_I2_1024x576@29.97_60.mp4
	- tos_I2_1024x576@30_60.mp4
	- tos_I2_1024x576@59.94_60.mp4
	- tos_I2_1024x576@60_60.mp4
	- tos_J1_1280x720@29.97_60.mp4
	- tos_J1_1280x720@30_60.mp4
	- tos_J1_1280x720@59.94_60.mp4
	- tos_J1_1280x720@60_60.mp4
	- tos_K1_1600x900@29.97_60.mp4
	- tos_K1_1600x900@30_60.mp4
	- tos_K1_1600x900@59.94_60.mp4
	- tos_K1_1600x900@60_60.mp4
	- tos_L1_1920x1080@29.97_60.mp4
	- tos_L1_1920x1080@29.97_60_2ndAudio[English].mp4
	- tos_L1_1920x1080@30_60.mp4
	- tos_L1_1920x1080@30_60_2ndAudio[English].mp4
	- tos_L1_1920x1080@59.94_60.mp4
	- tos_L1_1920x1080@59.94_60_2ndAudio[English].mp4
	- tos_L1_1920x1080@60_60.mp4
	- tos_L1_1920x1080@60_60_2ndAudio[English].mp4
	- tos_L2_1920x1080@29.97_60.mp4
	- tos_L2_1920x1080@30_60.mp4
	- tos_L2_1920x1080@59.94_60.mp4
	- tos_L2_1920x1080@60_60.mp4
	- tos_M1_2560x1440@59.94_60.mp4
	- tos_M1_2560x1440@60_60.mp4
	- tos_N1_3200x1800@59.94_60.mp4
	- tos_N1_3200x1800@60_60.mp4
	- tos_O1_3840x2160@59.94_60.mp4

**Comment by jpiesing** [comment]
@cta-source @haudiobe I believe this issue can be closed as the mezzanine content has been approved. Do you agree?

**Comment by mbergman42** [comment]
Yes, agreed.
