### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by nicholas-fr** [cta-wave/mezzanine#32]
We should consider adding the appropriate license information to this github repository, and related repos (e.g. Test-Content-Generation).

**Comment by jpiesing** [comment]
@mbergman42 ?

**Comment by jpiesing** [comment]
@cta-source Has this been addressed? If so, please close the issue.

**Comment by mbergman42** [comment]
It is resolved for this repo, but the original comment included "related repos".  I've done a scan of all CTA-WAVE repos, determined the action necessary, and am in the process of contacting contributors to those repos regarding adding license information.  I'll continue working it for a couple of weeks, then should be able to close it.

**Comment by t11s** [comment]
There should specific textual information regarding media licensing chain (both upstream source and downstream licensing) in the release directories (i.e. https://dash.akamaized.net/WAVE/Mezzanine/releases/1).

For example something like "The source material for Tears of Steel is licensed as Creative Commons Attribution 3.0 (https://creativecommons.org/licenses/by/3.0/) (CC) Blender Foundation | mango.blender.org, and the transformations in this directory maintain that same licensing."

**Comment by jpiesing** [comment]
> There should specific textual information regarding media licensing chain (both upstream source and downstream licensing) in the release directories (i.e. https://dash.akamaized.net/WAVE/Mezzanine/releases/1).
> 
> For example something like "The source material for Tears of Steel is licensed as Creative Commons Attribution 3.0 (https://creativecommons.org/licenses/by/3.0/) (CC) Blender Foundation | mango.blender.org, and the transformations in this directory maintain that same licensing."

@t11s If you look in the "under review" versions, each media file has a .json file of related metadata which includes the source licensing.

**Comment by t11s** [comment]
Aha, I see the license info in the json files of the under_review/2021-08-05/ directory, thanks for pointing that out, I have no further concerns and this issue should be resolved.

**Comment by nicholas-fr** [comment]
As license information is provided for this repo and for mezzanine content generated, I propose to close this issue and raise dedicated issues in other repos as needed.

**Comment by mbergman42** [comment]
Hi, that works for me.  I’m slowly working my way through all repos on licensing, by the way.

Mike Bergman
Consumer Technology Association, producer of CES®
d: +1(703) 907-4366
m: +1(609) 865-4402
