### ISSUE TITLE
add annotations to red and green frames at start and end

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/mezzanine#35]
From https://github.com/cta-wave/Test-Content/issues/12 ,

The red and green frames at the start and end of each stream should be annotated and be included in the frame number count & timecode.

**Comment by nicholas-fr** [comment]
New mezzanine content has been uploaded to:
https://dash.akamaized.net/WAVE/Mezzanine/new/20210608/

This now includes the annotations on the start and end frames, and the duration is exactly 60 seconds, without 2 additional frames.

![start (2)](https://user-images.githubusercontent.com/9865551/121209954-91591880-c87b-11eb-9608-4322036bc3be.png)

![end (2)](https://user-images.githubusercontent.com/9865551/121209988-97e79000-c87b-11eb-858f-5ab0d81ba404.png)

**Comment by jpiesing** [comment]
@andyburras @yanj-github Is this what you would expect based on the discussion in https://github.com/cta-wave/Test-Content/issues/12 ?

**Comment by andyburras** [comment]
Yes thanks. The red and green frames are now part of the observable content. We will adjust the observations to account for the frame zero start point.

**Comment by nicholas-fr** [comment]
@andyburras Would it make more sense for the mezzanine content annotations to start from frame 1 as before? 
I have an option in the script to determine the start frame (0 or 1), so I can change regenerate the content easily enough:

![start (3)](https://user-images.githubusercontent.com/9865551/121367384-9204b400-c93a-11eb-930b-c4a57d4a33a0.png)

![end (3)](https://user-images.githubusercontent.com/9865551/121369266-faa06080-c93b-11eb-9c59-5cb565b31de4.png)

**Comment by yanj-github** [comment]
Thanks @nicholas-fr if it starts from 1 ends 900 then it would be better for us.
@jpiesing @louaybassbouss is it fine with you too?

**Comment by jpiesing** [comment]
> Thanks @nicholas-fr if it starts from 1 ends 900 then it would be better for us.
> @jpiesing @louaybassbouss is it fine with you too?

No difference either way to me.

**Comment by louaybassbouss** [comment]
> Thanks @nicholas-fr if it starts from 1 ends 900 then it would be better for us.
> @jpiesing @louaybassbouss is it fine with you too?

@yanj-github fine for us as well

**Comment by jpiesing** [comment]
@nicholas-fr Please go with 1 to 900. Please close this issue when new 15-30-60 mezzanine streams have been uploaded.

**Comment by nicholas-fr** [comment]
The new 15/30/60fps mezzanine files have been uploaded here:
https://dash.akamaized.net/WAVE/Mezzanine/new/2021-06-10/
