### ISSUE TITLE
WAVE Splice: fractional framerate (14.985, 29.97, 59.94) CMAF Fragment duration considerations

### ISSUE THREAD

**Issue by rbouqueau** [cta-wave/mezzanine#40]
In my computations I considered an audio access unit duration of 1024 samples (i.e. 1024/48000 seconds).

With the constraint of CMAF Fragments alignment across audio 48khz and video Selection Sets:
- 25fps: 0.320s
- 30fps: 0.533...s
- 29.97fps: 21.25...s

I made the computation with 44.1khz audio for 29.97fps. My computed minimum duration is 3416.74...s. That doesn't seem usable but let me know if that's mandatory.

I suggest to use 2.133...s for 30fps (compatible with 15fps).

=====

As a trace, the computation consisted in finding two integer numbers so that ```AU_duration_audio * nb_AUs_audio = AU_duration_video * nb_AUs_video``` e.g. ``` 1024/48000 * nb_AUs_audio = 1001/30000 * nb_AUs_video ```. That gave:
 - 25 fps: ```15 * nb_AUs_audio = 8 * nb_AUs_video``` : CMAF Fragment duration base = 1024/48000 * 15
 - 30 fps: ```1001 * nb_AUs_audio = 640 * nb_AUs_video``` : CMAF Fragment duration base = 1024/48000 * 1001
 - 29.97 fps: ```147147 * nb_AUs_audio = 102400 * nb_AUs_video``` : CMAF Fragment duration base = 1024/48000 * 147147

**Comment by nicholas-fr** [comment]
The mezzanine content has been generated. Please see #18 for the details.
