### ISSUE TITLE
reducing generic mezzanine content length to match mezzanine content for splicing

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/mezzanine#43]
The mezzanine content to be used for splicing has a shorter length than the 60s used for the generic mezzanine content.

We should consider harmonising the length of the mezzanine content, e.g. reducing the generic mezzanine content to the same length as the splicing content.

**Comment by jpiesing** [comment]
The splice_main content is 10s which may be enough for sequential track playback (incl. content options), encrypted content playback but perhaps not for random access, switching set playback.
30s may be enough for the rest where 10s is too short.

**Comment by nicholas-fr** [comment]
In addition to the content for splicing tests, the following 30s mezzanine content was created and approved in mezzanine release v3:
    - croatia_L1_1920x1080@25_30.mp4
    - croatia_L1_1920x1080@50_30.mp4
    - tos_L1_1920x1080@29.97_30.mp4
    - tos_L1_1920x1080@30_30.mp4
    - tos_L1_1920x1080@59.94_30.mp4
    - tos_L1_1920x1080@60_30.mp4
    - croatia_LD1_1920x1080@25_7200.mp4
    - tos_LD1_1920x1080@30_7200.mp4

The 30s mezzanine was used to generate the appropriate test vectors in the latest batch created (2022-10-17), as defined in the [AVC test content sparse matrix](https://docs.google.com/spreadsheets/d/1hxbqBdJEEdVIDEkpjZ8f5kvbat_9VGxwFP77AXA_0Ao/edit#gid=0)
