### ISSUE TITLE
Audio mezzanine in under_review folder

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/mezzanine#49]
Currently audio mezzanine is under:
http://dash-large-files.akamaized.net/WAVE/Mezzanine/under_review/2022-04-01/

We are still waiting for them to be approved.
Are they ready to be move to released folder please?

**Comment by cta-source** [comment]
I believe this release was approved in the DPCTF meeting on 6/29. They can be moved now.

**Comment by rbouqueau** [comment]
Will this content be accompanied by the json metadata?

**Comment by cta-source** [comment]
No idea, what is the process for creating json metadata and what does it contain?

**Comment by nicholas-fr** [comment]
I believe this is referring to JSON equivalent to what is created for the video mezzanine? Correct me if I'm wrong.
E.g. http://dash-large-files.akamaized.net/WAVE/Mezzanine/under_review/2022-04-21/croatia_L1_1920x1080@25_30.json

**Comment by yanj-github** [comment]
@cta-source I believe we required "seed" and "license" so that it can be referenced from content generation script to put in mpd.
However, I dont know how much other values required for audio I can see creation date and version will be useful. 
Any comments please? And in case if I missed, do we have this json format documented anywhere what elements should be in there please?

**Comment by cta-source** [comment]
I think @nicholas-fr is doing a first cut. Meanwhile--not to interrupt that effort--I looked in the spec and didn't actually find a definition of the audio json format. Here are some candidate parameters with a suggested format:

- Seed (32 character string in hex format, e.g., "98626CE9659298B9316A26DE2C92AE91" -- does this format work, or should we have e.g. "0x" in front?)
- License (string--this text is already in the DPCTF spec, v1.22, section 5.3.4.2)
- Creation Date (string)
- Version (string)
- Frame Rate (Hz)
- Length (seconds)

Anyone have comments on these parameters? Is this work done already (@nicholas-fr, I think you were doing something?)

**Comment by nicholas-fr** [comment]
@cta-source, it's not done yet, but I plan to get it done over the next 2 weeks, hopefully this week as it should not take much time.
If this is urgent, someone else could step in now and pick this up, I don't want to block anything if I can help it.  Otherwise I'm happy to work on this shortly.

In any case, I think those parameters make sense.
Are there any additional audio bitstream properties that would be useful to capture, such as bits per sample, channel count?

**Comment by cta-source** [comment]
Bits per sample and channel count both make sense, thanks. Also, if the audio file is NOT white noise, we don't need the 'Seed" parameter. Can I just mark it "optional"? If so, the full list so far is (with some re-ordering):

- Channel count 
- Bits per sample 
- Frame Rate (Hz)
- Length (seconds) 
- License (string--this text is already in the DPCTF spec, v1.22, section 5.3.4.2)
- Version (string)
- Creation Date (string)
- Seed (for files that __are__ or __embed__ white noise: 32 character string in hex format, e.g., "98626CE9659298B9316A26DE2C92AE91" -- _does this format work, or should we have e.g. "0x" in front?_; files without white noise set this to 0)

**Comment by wschidol** [comment]
I feel that the format for seed is sufficient. To recreate the mezzanine, the command_line field can be used (see below) but the seed would uniquely characterize the audio in any case.

Frame rate is not typically used for PCM audio. What would typically be used is sampling rate, also in Hz, something like 48 kHz.

Comparing this with the json file for video, it would also be useful to retain
* label (string -- this can be used to label and distinguish an "english noise" vs. "german noise" mezzanine asset)
* command_line (string -- this would be the full command line to (re)generate the pseudo noise content)
* URI (how else would the json qualify where the mezzanine resides?)

Therefore, the full list of fields would be

* Channel count
* Bits per sample
* Sample Rate (Hz)
* Length (seconds)
* License (string--this text is already in the DPCTF spec, v1.22, section 5.3.4.2)
* Version (string)
* Creation Date (string)
* Seed (for files that are or embed white noise: 32 character string in hex format, e.g., "98626CE9659298B9316A26DE2C92AE91"; files without white noise set this to 0)
* Label (string)
* URI (URL relative to json file location)

If there are no objections, we can go ahead and create json files for the existing mezzanine files.

**Comment by jpiesing** [comment]
> Was there any update on this?

JSON files exist. Early versions have been uploaded to http://dash-large-files.akamaized.net/WAVE/Mezzanine/under_review/2022-04-01/ but these may now be out of date as some comments from @yanj-github are being addressed.

**Comment by nicholas-fr** [comment]
The JSON are now up to date and include the fixes for the comments I received from Yan and Jan.

The version indicated is the mezzanine release version which will be v3 (which follows the same semantics as the video mezzanine). If we want to use different semantics for the version, then that would need discussion.

Lastly, the filenames were left as provided, e.g. "PN01v02". 
If that needs to change, then that is also something to discuss.

**Comment by rbouqueau** [comment]
PS @nicholas-fr : thank you. Beware that replacing files on the Akamai server is not a good idea due to the aggressive caching policy.

**Comment by yanj-github** [comment]
@nicholas-fr  are you planning to upload it again because of this caching issue of Akamai? 
As this is now all checked and agreed if it the better idea to upload it to the final location which is release folder? http://dash-large-files.akamaized.net/WAVE/Mezzanine/releases/ 

Another question is when the mezzanine is reviewed and released and move to the releases folder will the date and version changes? If the date and version changes please note that the regeneration is required as which need to be referenced on mpd. 
We would prefer not change creation date and version when releasing the mezzanine.

**Comment by nicholas-fr** [comment]
@yanj-github I have uploaded new versions that no longer have the version in the filename (or in the name in the JSON files), as versioning should be managed via the mezzanine release version, as I understand it:
https://dash-large-files.akamaized.net/WAVE/Mezzanine/under_review/2022-10-03/
I propose to use these.

>when the mezzanine is reviewed and released and move to the releases folder will the date and version changes?

For the audio, as it is already using version 3 I will leave both the version and creation_date unchanged.

I will regenerate the JSON for all the video files (to update the version to 3 for this new release). 
For those files, the JSON creation_date will be changed to the current date. Please let me know if you have any concerns about this.

I'm putting together all the files for a v3 mezzanine release (unchanged, changed and new) and hope to upload them all tomorrow. I'll send out an email when release 3 is ready so anyone interested can have a look and review.

**Comment by yanj-github** [comment]
I can see these are now released https://dash.akamaized.net/WAVE/Mezzanine/releases/3
If everyone is happy then I will close this issue.
