### ISSUE TITLE
Different Resolutions for Video

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/mezzanine#5]
We need to generate the different resolutions for the video according to the agreements in 
https://onedrive.live.com/View.aspx?resid=7F5F9BF849BBE975!1208&authkey=!APJx__1ed3MNDFw

**Comment by jpiesing** [comment]
I don't remember a final decision on which combinations of resolutions and frame rates would be generated.

Feedback from @nicholas-fr  is that QR codes are not readable at 192x108 so I suggest dropping that resolution. They are readable (slowly) at  320x180 and OK at all higher resolutions.

So I make the following proposal.

1) Tears of steel at 60Hz in 14 resolutions 
1. 1920 | 1080
2. 1600 | 900
3. 1280 | 720
4. 1024 | 576
5. 960 | 540
6. 852 | 480
7. 768 | 432
8. 720 | 404
9. 704 | 396
10. 640 | 360
11. 512 | 288
12. 480 | 270
13. 384 | 216
14. 320 | 180

2. Croatia at 50Hz in those same 14 resolutions.

3. Tears of Steel at 60/1.001Hz in the first 8 resolutions (down to and including 720x404 but no lower).

We may want to consider a couple of resolutions of Croatia at 60Hz in the future for HDR/BT.2100.

**Comment by haudiobe** [comment]
Call 2020/07/27: Lowest resolutions are too low QR code detection. We start from 480x270. Agreed. For Croatia and ToS, there are also higher resolutions. @nicholas-fr provides 4k: http://dash-large-files.akamaized.net/WAVE/Mezzanine/ Need to be regenerated to start from A at 480. We also should and index N[1,2] to be able to generate the same resolution CMAF-Tracks. Maybe go to 3 at 2160, 1080 and 720.
