### ISSUE TITLE
Available audio mezzanine information and URL

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/mezzanine#54]
The Device Observation Framework (OF) relies on the audio mezzanine content being available locally in order to compare with the recorded audio, and observations to be reported.

Currently the mezzanine URLs are hard coded so when changes occur the OF needs to be manually updated. To avoid issues with the OF referencing incorrect audio, we would like to request a simple database.json file on the mezzanine github repo which is updated when the mezzanine changes. This would need to contain the audio file name, md5 hash and URL, example as follows:

database.json
{
    "audio": {
        "PN01": {
            "md5": "5085c51b8c1cebdc557eabd2571e6aef",
            "path": "[https://dash.akamaized.net/WAVE/Mezzanine/releases/3/PN01.wav"](https://dash.akamaized.net/WAVE/Mezzanine/releases/3/PN01.wav%22)
        }
        "PN02": { ... ...}
... ...
}

**Comment by yanj-github** [comment]
Thanks @nicholas-fr  you have sugguested us to get these information from json file on akamai server which is fine. 
However we still need a list of avablible audio mezzanine to download to observation framework and location of json fie to get informaiton from.

database.json
{
"audio": {
"PN01": {
"path": "[https://dash.akamaized.net/WAVE/Mezzanine/releases/3/PN01.wav"](https://dash.akamaized.net/WAVE/Mezzanine/releases/3/PN01.wav%22),
"json_path": "https://dash.akamaized.net/WAVE/Mezzanine/releases/3/PN01.json"
}
"PN02": { ... ...}
... ...
}

**Comment by gitwjr** [comment]
@nicholas-fr to generate the database.json for audio mezzanine.

**Comment by nicholas-fr** [comment]
Created using [`adb_update.py`](https://github.com/cta-wave/mezzanine/blob/master/adb_update.py), now available here:
https://github.com/cta-wave/mezzanine/raw/master/metadata/audio_mezzanine_database.json

@yanj-github Please have  a look and let me know if this is what you need.

**Comment by yanj-github** [comment]
Thank you very much @nicholas-fr  this is looking good to me.
Just one note for your script [adb_update.py](https://github.com/cta-wave/mezzanine/blob/master/adb_update.py), we assume audio mezzanine always start with PN and .wav. I think this is always the case then we are fine.
