### ISSUE TITLE
Create Beeps/Flashes such that they are not integer

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/mezzanine#6]
Some discussion on e-mail - copy here

**Comment by jpiesing** [comment]
Eurofins email said;
This project was started by BBC R&D to address a similar problem (but for timing across companion screens). It might help:
https://github.com/bbc/dvbcss-synctiming/tree/master/test_sequence_gen
Or, if someone would just find a way to pay us for the work involved, we could save you all a lot of time and effort.
Thanks
Bob

**Comment by nicholas-fr** [comment]
This should be resolved by #8 which makes use of the abovementioned BBC R&D scripts.

**Comment by technogeek00** [comment]
Agreed this should be closed now

**Comment by haudiobe** [comment]
Call 2020/07/27: Covered - thanks
