### ISSUE TITLE
Audio only Beeps

### ISSUE THREAD

**Issue by haudiobe** [cta-wave/mezzanine#7]
We would need a good audio track that would also add the beeps as agreed upon for both croatia and ToS.

**Comment by nicholas-fr** [comment]
The proposal in #8 makes use of the original source audio, mixing it with the A/V sync pattern beeps. So, for example, lip-sync can be manually observed when using Tears of Steel, in addition to automated verification using the A/V sync test pattern.
If this is a valid approach, the weighting of beeps vs original audio may need adjusting.

**Comment by haudiobe** [comment]
Call 2020/07/27: Covered - thanks
